### ISSUE TITLE
Missing elements @Signin.js

### ISSUE THREAD

**Issue by Kiesen** [auth0-samples/react-redux-centralized-login#1]
Username and password input fields are missing but declared. If i have some time i will open a PR. 
Nevertheless thanks for this example, it helped me a lot.   
![auth0-react-redux](https://user-images.githubusercontent.com/7195750/31554130-ed874268-b03c-11e7-8766-56f742ce886a.png)

**Comment by gpolyn** [comment]
+1

Must say: kind of lame -- has to be said! The .gif accompanying the demo clearly shows the input fields -- their omission is so disruptive that it's kind of hard to believe. Took me 20 minutes just to accept that, indeed, the most vital fields in the whole demo are missing!

**Comment by arcseldon** [comment]
It is centralized login. Just press the Submit button... :)

This was based from another sample I hand-wrote, which used an embedded login. 

Any reference to the fields is just legacy from that refactor for this sample (using Centralized Login aka. Auth0 Hosted Login Page). Auth0 hosts the login form, not the application.

**Comment by arcseldon** [comment]
Updated gif. Closing on basis it is understood that Auth0 hosts the login page.

If you are looking for embedded login page (application hosted login form fields) - please see [this sample](https://github.com/auth0-samples/react-redux-embedded-login)

**Comment by gpolyn** [comment]
...'Submit' button label suggests form fields, somewhere.
